url: http://opendatakraken.org

# Site settings
title: Open Data Kraken
email: opendatakraken@gmail.com
description: "Smart tools for data manipulation and visualization"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: E02C10
  secondary: 944918  
  secondary-dark: 472006

# Team names, titles and social links
people:
- name: Open Data Kraken
  pic: kraken
  position: Lead Engineer
  social:
    - title: github
      url: https://github.com/opendatakraken
- name: Open Business Intelligence
  pic: openbi
  position: Lead Engineer
  social:
    - title: github
      url: https://github.com/openbusinessintelligence
- name: Nicola Marangoni
  pic: niko
  position: Lead Engineer
  social:
    - title: github
      url: https://github.com/nicolamarangoni

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/opendk

# Postal address (add as many lines as necessary)
address:
  - line: Somewhere
  - line: The World

# Build settings
markdown: kramdown
permalink: pretty